import Link from "next/link";
import { getLivingCostCities, getLivingCostCity } from "@/lib/living-cost/queries";
import CityComparisonChart from "./CityComparisonChart";
import CitySelector from "./CitySelector";

export const dynamic = "force-dynamic";

const yen = (value: number | null) => value === null ? "Unavailable" : `¥${value.toLocaleString()}`;

export default async function LivingCostPage({ searchParams }: { searchParams: { city?: string } }) {
  const cities = await getLivingCostCities();
  if (!cities.length) return <main className="container py-16"><h1 className="text-4xl font-bold">Japan Living Cost Guide</h1><p className="card mt-8 p-6 text-slate-600">No city data is available yet. Import the provided workbook to load the guide.</p></main>;

  const selectedName = cities.some((city) => city.city.toLowerCase() === searchParams.city?.toLowerCase()) ? cities.find((city) => city.city.toLowerCase() === searchParams.city?.toLowerCase())!.city : cities[0].city;
  const selected = await getLivingCostCity(selectedName);
  const summary = selected?.summary;
  const recommendations = cities.filter((city) => city.hasLivingCostData).sort((a, b) => (b.potentialRemainingIncome ?? -Infinity) - (a.potentialRemainingIncome ?? -Infinity)).slice(0, 3);

  return <main className="container py-12">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-semibold text-ocean">PLAN WITH REAL DATA</p><h1 className="mt-3 text-4xl font-bold">Japan Living Cost Guide</h1><p className="mt-3 max-w-2xl text-slate-600">Estimated monthly planning values based on the imported Numbeo dataset. Actual costs may vary and these estimates are not financial advice.</p></div><CitySelector cities={cities.map((city) => city.city)} selected={selectedName}/></div>
    {summary ? <>
      <section className="mt-10 grid gap-5 md:grid-cols-3"><div className="card p-6"><p className="text-sm font-semibold text-slate-500">ESTIMATED MONTHLY COST</p><p className="mt-3 text-3xl font-bold text-ocean">{yen(summary.estimatedMonthlyCost)}</p></div><div className="card p-6"><p className="text-sm font-semibold text-slate-500">AVERAGE NET SALARY</p><p className="mt-3 text-3xl font-bold">{yen(summary.averageNetSalary)}</p></div><div className="card bg-ink p-6 text-white"><p className="text-sm font-semibold text-slate-300">POTENTIAL REMAINING INCOME</p><p className={`mt-3 text-3xl font-bold ${(summary.potentialRemainingIncome ?? 0) < 0 ? "text-red-300" : "text-emerald-300"}`}>{yen(summary.potentialRemainingIncome)}</p></div></section>
      <section className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="card p-7"><div className="flex items-center justify-between"><div><p className="font-semibold text-ocean">COST BREAKDOWN</p><h2 className="mt-2 text-2xl font-bold">{selectedName} per month</h2></div><Link className="text-sm font-bold text-ocean" href={`/calculators?city=${encodeURIComponent(selectedName)}`}>Customize calculator →</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{Object.entries(summary.breakdown).map(([key, value]) => <div className="rounded-lg bg-slate-50 p-4" key={key}><p className="text-sm capitalize text-slate-500">{key}</p><p className="mt-1 text-xl font-bold">{yen(value)}</p></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Food uses the inexpensive restaurant meal multiplied by 30. Entertainment uses four cinema tickets. This is an application planning assumption, not an official Numbeo monthly total.</p></div><div className="card p-7"><p className="font-semibold text-ocean">RECOMMENDED CITIES</p><h2 className="mt-2 text-2xl font-bold">App recommendations</h2><p className="mt-2 text-sm text-slate-500">Sorted by estimated remaining income among cities with complete data.</p><div className="mt-5 space-y-3">{recommendations.map((city, index) => <Link className="block rounded-lg border border-slate-200 p-4 hover:border-ocean" href={`/living-cost?city=${encodeURIComponent(city.city)}`} key={city.city}><div className="flex justify-between"><span className="font-bold">{index + 1}. {city.city}</span><span className="font-bold text-emerald-600">{yen(city.potentialRemainingIncome)}</span></div><p className="mt-1 text-sm text-slate-500">Estimated cost {yen(city.estimatedMonthlyCost)} · net salary {yen(city.averageNetSalary)}</p></Link>)}</div></div></section>
      <section className="card mt-8 p-7"><p className="font-semibold text-ocean">CITY COMPARISON</p><h2 className="mt-2 text-2xl font-bold">Cost, salary, and remaining income</h2><div className="mt-6"><CityComparisonChart cities={cities}/></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3">City</th><th className="p-3">Monthly cost</th><th className="p-3">Net salary</th><th className="p-3">Remaining income</th></tr></thead><tbody>{cities.map((city) => <tr className="border-b last:border-0" key={city.city}><td className="p-3 font-semibold"><Link className="text-ocean" href={`/living-cost?city=${encodeURIComponent(city.city)}`}>{city.city}</Link></td><td className="p-3">{yen(city.estimatedMonthlyCost)}</td><td className="p-3">{yen(city.averageNetSalary)}</td><td className="p-3">{yen(city.potentialRemainingIncome)}</td></tr>)}</tbody></table></div></section>
      <p className="mt-6 text-xs text-slate-500">Source: {summary.source} · Currency: {summary.currency} · Data record updated: {new Date(summary.updatedAt).toLocaleDateString("en-US")}</p>
    </> : <p className="card mt-10 p-6 text-slate-600">Living-cost data for {selectedName} is unavailable. Hiroshima is intentionally not included because the supplied dataset contains no usable price table for it.</p>}
  </main>;
}
