import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
const prisma = new PrismaClient();
async function main() {
  await Promise.all([prisma.jobApplication.deleteMany(), prisma.savedJob.deleteMany(), prisma.job.deleteMany(), prisma.company.deleteMany(), prisma.location.deleteMany(), prisma.jobCategory.deleteMany(), prisma.skill.deleteMany(), prisma.japaneseLevel.deleteMany(), prisma.salaryData.deleteMany(), prisma.visaInformation.deleteMany(), prisma.costOfLiving.deleteMany(), prisma.resource.deleteMany()]);
  const levels = await Promise.all(["N5","N4","N3","N2","N1"].map((code,i)=>prisma.japaneseLevel.create({data:{code,label:`JLPT ${code}`,description:`Practical benchmark for ${code} learners.`}})));
  const [tech,design,education] = await Promise.all(["Technology","Design","Education"].map((name)=>prisma.jobCategory.create({data:{name,slug:name.toLowerCase()}})));
  const [tokyo,osaka,kyoto] = await Promise.all([["Tokyo","Tokyo","Japan’s global hub for technology and international teams."],["Osaka","Osaka","An energetic, welcoming city with a lower cost of living."],["Kyoto","Kyoto","A creative city blending tradition, tourism and innovation."]].map(([name,prefecture,description])=>prisma.location.create({data:{name,slug:name.toLowerCase(),prefecture,description}})));
  await Promise.all([[tokyo.id,120000],[osaka.id,85000],[kyoto.id,80000]].map(([locationId,monthlyRent])=>prisma.costOfLiving.create({data:{locationId:locationId as string,monthlyRent:monthlyRent as number,monthlyEssentials:70000,transport:12000}})));
  const [js,python,ux] = await Promise.all([["JavaScript","Engineering"],["Python","Engineering"],["UX Research","Design"]].map(([name,category])=>prisma.skill.create({data:{name,category}})));
  const companies = await Promise.all([["Sora Labs","sora-labs","Product technology for a more connected Japan.","Software"],["Mori Design","mori-design","Human-centred design studio with global clients.","Design"],["Hikari Learning","hikari-learning","Language and career education for new residents.","Education"]].map(([name,slug,description,industry])=>prisma.company.create({data:{name,slug,description,industry,website:"https://example.com"}})));
  const jobs = await Promise.all([
    prisma.job.create({data:{title:"Frontend Engineer",slug:"frontend-engineer-sora",description:"Join a bilingual product team building tools used by millions across Asia.",employmentType:"FULL_TIME",minSalary:5500000,maxSalary:8000000,visaSupport:true,remote:true,companyId:companies[0].id,locationId:tokyo.id,categoryId:tech.id,skills:{connect:[{id:js.id}]}}}),
    prisma.job.create({data:{title:"Product Designer",slug:"product-designer-mori",description:"Shape clear, delightful experiences for international customers.",employmentType:"FULL_TIME",minSalary:4500000,maxSalary:6800000,visaSupport:true,remote:false,companyId:companies[1].id,locationId:osaka.id,categoryId:design.id,skills:{connect:[{id:ux.id}]}}}),
    prisma.job.create({data:{title:"English Instructor",slug:"english-instructor-hikari",description:"Support learners with practical language and career confidence.",employmentType:"FULL_TIME",minSalary:3200000,maxSalary:4400000,visaSupport:true,remote:false,companyId:companies[2].id,locationId:kyoto.id,categoryId:education.id}})
  ]);
  await Promise.all([["Engineer","Tokyo","MID",5000000,7000000,9000000],["Designer","Osaka","MID",4000000,5600000,7500000],["Instructor","Kyoto","ENTRY",2800000,3400000,4300000]].map(([role,location,experienceLevel,minSalary,medianSalary,maxSalary])=>prisma.salaryData.create({data:{role:role as string,location:location as string,experienceLevel:experienceLevel as string,minSalary:minSalary as number,medianSalary:medianSalary as number,maxSalary:maxSalary as number}})));
  await Promise.all([["Engineer visa","engineer-humanities","For professional work in engineering, technology, education and humanities.","A relevant degree or 10 years’ experience plus a qualifying offer.","1–5 years","https://www.moj.go.jp/isa/"],["Highly skilled professional","highly-skilled","Points-based route for advanced professionals.","Points across education, income, experience and Japanese ability.","5 years","https://www.moj.go.jp/isa/"]].map(([name,slug,summary,requirements,typicalDuration,officialUrl])=>prisma.visaInformation.create({data:{name,slug,summary,requirements,typicalDuration,officialUrl}})));
  const passwordHash=await bcrypt.hash("demo1234",12);
  await prisma.user.upsert({where:{email:"demo@example.com"},update:{},create:{email:"demo@example.com",name:"Demo Explorer",passwordHash,profile:{create:{targetCity:"Tokyo",japaneseLevelId:levels[2].id}}}});
  await prisma.resource.createMany({data:[{title:"Japan visa pathways explained",category:"Visa",summary:"Plain-language overview of work, student and dependent routes.",url:"https://www.moj.go.jp/isa/",featured:true},{title:"Japanese resume checklist",category:"Career",summary:"Format and chronology tips for a strong first application.",url:"#",featured:true}]});
  console.log(`Seeded ${jobs.length} jobs, ${companies.length} companies, 3 locations and domain reference data.`);
}
main().finally(()=>prisma.$disconnect());
