"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

const inputClass = "mt-2 w-full rounded-md border border-slate-300 bg-white px-3 py-3 text-base text-slate-900 outline-none transition focus:border-ocean focus:ring-2 focus:ring-blue-100 disabled:cursor-not-allowed disabled:bg-slate-100";

export default function Signup() {
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmation, setShowConfirmation] = useState(false);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget)); if (data.password !== data.confirm) { setError("Passwords do not match."); return; } setSubmitting(true);
    try { const response = await fetch("/api/auth/signup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (response.ok) { window.location.assign("/dashboard"); return; } setError(await response.text()); } catch { setError("We could not create your account. Please try again."); } finally { setSubmitting(false); }
  }

  function passwordInput(name: string, label: string, visible: boolean, setVisible: (value: boolean | ((current: boolean) => boolean)) => void) { return <label className="block text-sm font-bold text-slate-700">{label}<div className="relative"><input name={name} type={visible ? "text" : "password"} autoComplete="new-password" minLength={8} required disabled={submitting} className={`${inputClass} pr-16`}/><button type="button" onClick={() => setVisible((value) => !value)} disabled={submitting} className="absolute bottom-0 right-0 top-2 px-3 text-xs font-bold text-ocean hover:underline disabled:opacity-50" aria-label={visible ? `Hide ${label.toLowerCase()}` : `Show ${label.toLowerCase()}`}>{visible ? "Hide" : "Show"}</button></div></label>; }

  return <main className="container flex min-h-[calc(100vh-9rem)] items-center py-8 sm:py-12"><div className="grid w-full overflow-hidden rounded-lg border border-slate-200 bg-white shadow-[0_20px_60px_rgba(15,23,42,0.12)] lg:grid-cols-[.92fr_1.08fr]"><section aria-label="Japanese shrine in a peaceful landscape" className="relative min-h-64 overflow-hidden bg-slate-900 lg:min-h-[680px]" role="img" style={{ backgroundImage: "url('/images/japan-shine.jpg')", backgroundPosition: "center", backgroundSize: "cover" }}><div aria-hidden="true" className="absolute inset-0 bg-slate-950/40"/><div aria-hidden="true" className="absolute bottom-0 left-8 top-8 w-1 bg-red-500 lg:left-10 lg:top-10"/><div className="absolute bottom-8 left-8 right-8 text-white lg:bottom-12 lg:left-12 lg:right-12"><p className="text-sm font-bold tracking-[0.18em] text-slate-100">JAPAN CAREER &amp; LIVING</p><h2 className="mt-3 max-w-sm text-3xl font-bold leading-tight sm:text-4xl">A thoughtful start to your next chapter.</h2><div className="mt-6 h-px w-16 bg-red-400"/></div></section><section className="flex min-h-[610px] items-center px-6 py-10 sm:px-12 lg:px-16"><div className="mx-auto w-full max-w-md"><div className="flex items-center gap-3"><span aria-hidden="true" className="h-8 w-1 bg-red-500"/><p className="text-sm font-bold tracking-[0.16em] text-ocean">BEGIN YOUR PLAN</p></div><h1 className="mt-5 text-4xl font-bold text-slate-900">Create your workspace.</h1><p className="mt-3 text-base leading-7 text-slate-600">A few details now will shape the roles, cities, and move planning you see next.</p><form onSubmit={submit} aria-busy={submitting} className="mt-8 space-y-4"><label className="block text-sm font-bold text-slate-700">Your name<input name="name" autoComplete="name" required disabled={submitting} className={inputClass}/></label><label className="block text-sm font-bold text-slate-700">Email address<input name="email" type="email" autoComplete="email" required disabled={submitting} className={inputClass}/></label>{passwordInput("password", "Password", showPassword, setShowPassword)}{passwordInput("confirm", "Confirm password", showConfirmation, setShowConfirmation)}{error && <p className="rounded-md border border-red-200 bg-red-50 px-3 py-3 text-sm text-red-700" role="alert">{error}</p>}<button className="btn btn-primary w-full rounded-md py-3 disabled:cursor-not-allowed disabled:opacity-60" type="submit" disabled={submitting}>{submitting ? "Creating your workspace..." : "Create my workspace"}</button></form><p className="mt-7 border-t border-slate-200 pt-6 text-center text-sm text-slate-600">Already have an account? <Link className="font-bold text-ocean hover:underline" href="/login">Log in</Link></p></div></section></div></main>;
}