import { NextResponse } from "next/server";
import { z } from "zod";
import { currentUserId } from "@/lib/auth";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

const typeSchema = z.enum(["job", "location", "resource"]);
const jobSchema = z.object({ title: z.string().trim().min(2).max(120), slug: z.string().trim().min(2).max(140).regex(/^[a-z0-9-]+$/), description: z.string().trim().min(10).max(5000), employmentType: z.string().trim().min(2).max(40), minSalary: z.coerce.number().int().min(0), maxSalary: z.coerce.number().int().min(0), visaSupport: z.coerce.boolean(), remote: z.coerce.boolean(), companyId: z.string().min(1), locationId: z.string().min(1), categoryId: z.string().min(1) }).refine((value) => value.maxSalary >= value.minSalary, { message: "Maximum salary must be at least the minimum salary." });
const locationSchema = z.object({ name: z.string().trim().min(2).max(80), slug: z.string().trim().min(2).max(100).regex(/^[a-z0-9-]+$/), prefecture: z.string().trim().min(2).max(80), description: z.string().trim().min(10).max(1000) });
const resourceSchema = z.object({ title: z.string().trim().min(2).max(160), category: z.string().trim().min(2).max(80), summary: z.string().trim().min(10).max(1000), url: z.string().url(), featured: z.coerce.boolean() });

async function requireAdmin() { const id = currentUserId(); if (!id) return false; return (await db.user.findUnique({ where: { id }, select: { role: true } }))?.role === "ADMIN"; }
const forbidden = () => NextResponse.json({ error: "Administrator access is required." }, { status: 403 });
const invalid = (message: string) => NextResponse.json({ error: message }, { status: 400 });

export async function GET() { if (!(await requireAdmin())) return forbidden(); const [jobs, locations, resources, companies, categories] = await Promise.all([db.job.findMany({ include: { company: { select: { name: true } }, location: { select: { name: true } }, category: { select: { name: true } } }, orderBy: { createdAt: "desc" } }), db.location.findMany({ include: { _count: { select: { jobs: true } } }, orderBy: { name: "asc" } }), db.resource.findMany({ orderBy: { title: "asc" } }), db.company.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } }), db.jobCategory.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } })]); return NextResponse.json({ jobs, locations, resources, companies, categories }); }

export async function POST(req: Request) { if (!(await requireAdmin())) return forbidden(); const body = await req.json(); const type = typeSchema.safeParse(body.type); if (!type.success) return invalid("Choose valid content to create."); try { if (type.data === "job") { const parsed = jobSchema.safeParse(body.data); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Check the form fields."); return NextResponse.json({ item: await db.job.create({ data: parsed.data, include: { company: { select: { name: true } }, location: { select: { name: true } }, category: { select: { name: true } } } }) }, { status: 201 }); } if (type.data === "location") { const parsed = locationSchema.safeParse(body.data); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Check the form fields."); return NextResponse.json({ item: await db.location.create({ data: parsed.data }) }, { status: 201 }); } const parsed = resourceSchema.safeParse(body.data); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Check the form fields."); return NextResponse.json({ item: await db.resource.create({ data: parsed.data }) }, { status: 201 }); } catch { return invalid("This record could not be created. Check that the slug is unique and the selected references exist."); } }

export async function PATCH(req: Request) { if (!(await requireAdmin())) return forbidden(); const body = await req.json(); const type = typeSchema.safeParse(body.type); const id = z.string().min(1).safeParse(body.id); if (!type.success || !id.success) return invalid("Choose valid content to update."); try { if (type.data === "job") { const parsed = jobSchema.safeParse(body.data); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Check the form fields."); return NextResponse.json({ item: await db.job.update({ where: { id: id.data }, data: parsed.data, include: { company: { select: { name: true } }, location: { select: { name: true } }, category: { select: { name: true } } } }) }); } if (type.data === "location") { const parsed = locationSchema.safeParse(body.data); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Check the form fields."); return NextResponse.json({ item: await db.location.update({ where: { id: id.data }, data: parsed.data }) }); } const parsed = resourceSchema.safeParse(body.data); if (!parsed.success) return invalid(parsed.error.issues[0]?.message ?? "Check the form fields."); return NextResponse.json({ item: await db.resource.update({ where: { id: id.data }, data: parsed.data }) }); } catch { return invalid("This record could not be updated. Check that the slug is unique and the selected references exist."); } }

export async function DELETE(req: Request) { if (!(await requireAdmin())) return forbidden(); const body = await req.json(); const type = typeSchema.safeParse(body.type); const id = z.string().min(1).safeParse(body.id); if (!type.success || !id.success) return invalid("Choose valid content to remove."); if (type.data === "location" && (await db.job.count({ where: { locationId: id.data } })) > 0) return invalid("Move or remove the jobs using this location before deleting it."); try { if (type.data === "job") await db.$transaction([db.savedJob.deleteMany({ where: { jobId: id.data } }), db.jobApplication.deleteMany({ where: { jobId: id.data } }), db.job.delete({ where: { id: id.data } })]); else if (type.data === "location") await db.location.delete({ where: { id: id.data } }); else await db.resource.delete({ where: { id: id.data } }); return NextResponse.json({ ok: true }); } catch { return invalid("This record could not be removed."); } }